### ISSUE TITLE
Real time object detection along with face detection

### ISSUE THREAD

**Issue by amulyaashetty** [Tech-Matrix/Face-Detection#1]
**Is your feature request related to a problem? Please describe.**
The existing code can only detect faces , I would like to add new features so that it detect objects as well.

**Describe the solution you'd like**
I would like to make use of mobilenet SSD to detect the objects in the background along with faces by initializing the list of class labels to detect and generate a set of bounding box  for each object and face detected with labels. 

**Describe alternatives you've considered**
Numpy library for face and object detection
Mobilenet SSD - single shot multibox detector to enhance the accuracy of detection.
![detection](https://user-images.githubusercontent.com/79209035/133472667-add2a547-1ef6-4892-bd71-200039d33e2e.PNG)

**Additional context**

**Comment by charvibannur** [comment]
Great initiative!! You can get started
