### ISSUE TITLE
Face and object detection in a given image

### ISSUE THREAD

**Issue by amulyaashetty** [Tech-Matrix/Face-Detection#2]
I would like to add image detection along with face detection using opencv , numpy and Mobilenet SSD , to generate bounding boxes around each object or face that is recognized  with accurate labels and percentage of accuracy of the detection. 
![Capture](https://user-images.githubusercontent.com/79209035/133477521-5db291f3-5263-40be-afd1-f6b0cbb83bc1.PNG)

**Comment by Mohamed-Ayaan358** [comment]
I am interested in this issue (Mohamed Ayaan)

**Comment by charvibannur** [comment]
I've assigned it. You can get started.
