### ISSUE TITLE
Emotion Recognition for Face Detection

### ISSUE THREAD

**Issue by urmilkalaria** [Tech-Matrix/Face-Detection#3]
**Is your feature request related to a problem? Please describe.**
In the current program the face detection, I am willing to add Emotion recognition using python and its libraries, this will help to understand the mood of the person using the app.

**Describe the solution you'd like**
This feature will help to recognize the facial expression such as angry, sad, happy, etc. and will display in the screen

**Describe alternatives you've considered**
I will be using python to inmplement the following thing.

**Additional context**
![Screenshot from 2021-09-16 17-23-42](https://user-images.githubusercontent.com/77614620/133607684-6e433533-804a-4c2c-b45d-ccb3a0e08beb.png)
Something of this sort of thing I am Planning to implement.

**Comment by A-HK** [comment]
Ahh that's a good one @urmilkalaria !
You can go ahead, I've assigned you.
